#########################################################
#                  FEED THE DOG - MORNING               #
#########################################################

- alias: "Feed The Dog Morning Weekdays"
  initial_state: True
  trigger:
    platform: time
    at: '07:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.feed_dog_reminder
  # action:
  #   - service: script.turn_on
  #     entity_id: script.master_bedroom_fan_low

- alias: "Feed The Dog Morning Weekends"
  initial_state: True
  trigger:
    platform: time
    at: '07:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    service: script.feed_dog_reminder

#########################################################
#                  FEED THE DOG - EVENING               #
#########################################################

- alias: "Feed The Dog Evening"
  initial_state: True
  trigger:
    platform: time
    at: '17:30'
  action:
    service: script.feed_dog_reminder
