- alias: 'Hass Startup Notification'
  initial_state: True
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data:
        name: midnight

    - service: script.wallpanel_relaunch