- alias: "Porch Light ON"
  initial_state: True
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: homeassistant.turn_on
      entity_id: light.porch_light
      data:
        brightness: 150
        transition: 30

- alias: 'Dim down porch light'
  initial_state: True
  trigger:
    - platform: time
      at: "22:00:00"
  action:
    - service: light.turn_on
      entity_id: light.porch_light
      data:
        brightness: 15
        transition: 60

- alias: "Sunrise Lighting Control"
  initial_state: True
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id: light.porch_light
    - service: homeassistant.turn_on
      entity_id: switch.shelly1pm_mqtt
