- alias: 'Hass Startup Notification'
  initial_state: True
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.telbot_david
      data:
        message: 'Hass.io is back up as of {{now().strftime("%H:%M:%S")}}'
    - service: script.audio_notify
      data_template:
        tts_msg: "Home Assistant has Restarting"
        mplayer: "echo_dot_main"

- alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: updater.updater
  condition:
    - condition: template
      value_template: "{{ states('updater.updater') != 'unknown' }}"
  action:
    - service: notify.telbot_david
      data_template:
        message: "Home Assistant {{ states.updater.updater.state }} is now available."

- alias: "Battery is low in Sensor"
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.office_motion_sensor,sensor.tradfri_remote_control,sensor.exterior_motion_sensor
      below: 20
  action:
    - service: notify.telbot_david
      data_template:
        message: '{{trigger.from_state.attributes.friendly_name}} Battery is below 20%'

- alias: "Tell David to leave for work"
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.my_event_offset_1
      from: 'off'
      to: 'on'
  condition:
    - condition: template 
      value_template: >
        {% if is_state('person.david', 'home') %} true
        {% elif is_state('person.david', 'not_home') %} true
        {% else %} false {% endif %}
    - condition: template 
      value_template: >
        {% if state_attr('calendar.disney_work_schedule', 'description') == ''  %} true
        {% else %} false {% endif %}
  action:
    - service: notify.mobile_app_david_pixel_3a_app
      data:
        message: "Time to leave for Work"

- alias: 'Pond Filter Issue'
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.pond_filter_status # Sensor8	(Pond Filter)
      from: 'off'
      to: 'on'
      for:
        seconds: 60
  action:
    - service: notify.telbot_david
      data:
        message: 'The pond filter may have an issue as of {{now().strftime("%H:%M")}}'

- alias: "Internet Speed Connection Poor"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.speedtest_download')|float < 120 }}"
  action:
    - service: notify.telbot_david
      data:
        message: "Internet Speed is {{ sensor.speedtest_download}}"

- alias: Notify for new devices
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.mobile_app_david_pixel_3a_app
      data_template:
        message: >
          New device:
          {{trigger.event.data.host_name}}
          ({{trigger.event.data.entity_id}})
        title: New device

- alias: Announce temp cooler outside
  initial_state: True
  trigger:
    - platform: template 
      value_template: "{{ states('sensor.echo_temperature') | int -2 > state_attr('weather.dark_sky', 'temperature')}}"
  condition:
    - condition: time
      after: '15:00:00'
      before: '21:00:00'
  action:
    - service: script.audio_notify
      data_template:
        tts_msg: "its now cooler outside than inside"
        mplayer: "echo_dot_main"