# - alias: "Georgina Leaving Work"
#   initial_state: True
#   trigger:
#     - platform: state
#       entity_id: person.georgina
#       from: jwc office
#       to: not_home
#   action:
#     - service: notify.mobile_app_david_pixel_3a_app
#       data:
#         message: "Georgina has left Work as of {{ now().strftime(%H:%M) }} "

- alias: "Georgina is Home"
  initial_state: True
  trigger:
    - platform: state
      entity_id: person.georgina
      from: 'not_home'
      to: 'home'
  # condition:
  #   - condition: numeric_state
  #     entity_id: sensor.time_online
  #     above: .5
  #   - condition: template 
  #     value_template: >
  #       {% if is_state('input_boolean.david_sleeping', 'off') %} true
  #       {% elif is_state('person.david', 'home') %} true
  #       {% else %} false {% endif %}
    # - condition: state
    #   entity_id: person.georgina
    #   state: 'not_home'
    #   for:
    #     minutes: 5
  action:
    - service: notify.mobile_app_david_pixel_3a_app
      data:
        message: "Georgina is Home"
        # message: "Georgina is Home as of {{now().strftime(%H:%M)}}"
    - service: script.audio_notify
      data_template:
        tts_msg: "Georgina is Now Home"
        mplayer: "echo_dot_main"

- alias: "David is Home"
  initial_state: True
  trigger:
    - platform: state
      entity_id: person.david
      from: 'not_home'
      to: 'home'
  condition:
    - condition: numeric_state
      entity_id: sensor.time_online
      above: .5
    - condition: template 
      value_template: >
        {% if is_state('input_boolean.georgina_sleeping', 'off') %} true
        {% elif is_state('person.georgina', 'home') %} true
        {% else %} false {% endif %}
  action:
    - service: notify.mobile_app_georgina_pixel_3a_xl_app
      data:
        message: "David is Now Home"
    - service: script.audio_notify
      data_template:
        tts_msg: "David is Now Home"
        mplayer: "echo_dot_main"