- alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: updater.updater
  condition:
    - condition: template
      value_template: "{{ states('updater.updater') != 'unknown' }}"
  action:
    - service: notify.telbot_david
      data_template:
        message: "Home Assistant {{ states.updater.updater.state }} is now available."

- alias: "Battery is low in Sensor"
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.office_motion_sensor,sensor.tradfri_remote_control,sensor.exterior_motion_sensor
      below: 20
  action:
    - service: notify.telbot_david
      data_template:
        message: '{{trigger.from_state.attributes.friendly_name}} Battery is below 20%'

- alias: "Internet Speed Connection Poor"
  trigger:
    - platform: template
      value_template: "{{ states('sensor.speedtest_download')|float < 120 }}"
  action:
    - service: notify.telbot_david
      data:
        message: "Internet Speed is {{ sensor.speedtest_download}}"

- alias: Announce temp cooler outside
  initial_state: True
  trigger:
    - platform: template 
      value_template: "{{ states('sensor.echo_temperature') | int -2 > state_attr('weather.dark_sky', 'temperature')}}"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '15:00:00'
        before: '21:00:00'
      - condition: state
        entity_id: group.window_sensors
        state: 'off'
  action:
    - service: script.audio_notify
      data_template:
        tts_msg: "its now cooler outside than inside"
        mplayer: "echo_dot_main"

# - alias: 'Pond Filter Issue'
#   initial_state: True
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.pond_filter_status  #Sensor8 (Pond Filter)
#       from: 'off'
#       to: 'on'
#       for:
#         seconds: 60
#   action:
#     - service: notify.telbot_david
#       data:
#         message: 'The pond filter may have an issue as of {{now().strftime("%H:%M")}}'
