#########################################################
#                                                       #
#               NOTIFY IF DEVICE OFFLINE                #
#                                                       #
#########################################################

- alias: "Notify if Camera is Offline"
  initial_state: true
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.frontdoor_camera
        - binary_sensor.frontyard_camera
        - binary_sensor.backyard_camera
        - binary_sensor.sideyard_camera
      from: 'on'
      to: 'off'
      for:
        seconds: 60
  action:
    - service: notify.telbot_david
      data:
        message: '{{ trigger.to_state.attributes.friendly_name }} has gone offline as of {{now().strftime("%H:%M")}}'

- alias: "DeCONZ Lights Unavailable"
  initial_state: True
  trigger:
    - platform: state
      entity_id: light.david_nightstand,light.georgina_nightstand,light.dining_floor_lamp,light.kitchen_pendant_1,light.kitchen_pendant_2,light.living_room_light_1,light.living_room_light_2,light.office_desk_light,light.porch_light,light.sideyard_light,light.kitchen_wetbar_rgbw
      to: unavailable
      for:
        minutes: 1
  action:
    - service: notify.telbot_david
      data_template:
        message: '{{trigger.from_state.attributes.friendly_name}} is Offline'