# Turns on lights 30 minutes before sunset if people are home
- alias: 'Kitchen on in the evening'
  initial_state: True
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: light.kitchen_pendants
      data:
        brightness: 203
        transition: 4

# Turn Light on for Dog when Away
- alias: 'Nightlight for Dog'
  initial_state: True
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'not_home'
  action:
    - service: light.turn_on
      entity_id: light.living_room_light_2
      data:
        brightness: 15
        transition: 4

# Turn off lights when everybody leaves the house
- alias: 'Lights Out when leaving'
  initial_state: True
  trigger:
    - platform: state
      entity_id: 
        - person.david
        - group.persons
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.time_online
        above: .10 #Six Minutes
      - condition: template 
        value_template: >
          {% if is_state('input_boolean.georgina_sleeping', 'on') %} true
          {% elif is_state('person.georgina', 'not_home') %} true
          {% else %} false {% endif %}
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.interior_lights

# Light on when getting home
- alias: "Light on when getting home"
  initial_state: True
  trigger:
    - platform: state
      entity_id: 
        - person.david
        - person.georgina
      from: 'not_home'
      to: 'home'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    - service: homeassistant.turn_on
      entity_id:
        - light.dining_floor_lamp
        - light.kitchen_pendants
      data:
        brightness: 203
        transition: 4
