- alias: "Georgina is Awake"
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.georgina_sleeping
      to: 'off'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: script.lights_on_when_georgina_awake

- alias: "Wake up David for Work"
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.my_event_offset_2
      from: 'off'
      to: 'on'
  condition: 
    - condition: template 
      value_template: >
        {% if is_state('person.david', 'home') %} true
        {% else %} false {% endif %}
    # - condition: template 
    #   value_template: >
    #     {% if state_attr('calendar.disney_work_schedule', 'description') == ''  %} true
    #     {% else %} false {% endif %}
  action:
    - service: notify.mobile_app_david_pixel_3a_app
      data:
        message: "Wake up for Work"
    - service: script.lights_on_when_david_awake

- alias: "Reset David Sleeping"
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.david_pixel_3a_app_is_charging
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.david_sleeping
      state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.david_sleeping

- alias: "Reset Georgina Sleeping"
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.georgina_pixel_3a_xl_app_is_charging
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.georgina_sleeping
      state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.georgina_sleeping