language: python
python:
  - "3.7"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - sed -e '/hacs/,+2d' < configuration.yaml > configuration.yaml
install:
  - wget http://ffmpeg.org/releases/ffmpeg-3.2.tar.bz2
  - tar -xjf ffmpeg-3.2.tar.bz2
  - cd ffmpeg-3.2
  - ./configure --disable-static --enable-shared --disable-doc --disable-yasm
  - make
  - sudo make install
  - cd ..
  - pip3 install -U setuptools
  - pip3 install homeassistant
  - pip3 install colorlog
script:
  - hass -c . --script check_config --info all
