language: python
python:
  - '3.8'
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - touch ./home-assistant_v2.db
  - touch ./home-assistant.log
  - sed -e '/hacs/,+5d' < configuration.yaml > configuration.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
