- id: '1595393405978'
  alias: window fan off at 73
  description: ''
  trigger:
  - below: '73.1'
    entity_id: sensor.bedroom_temperature
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.sonoff2
    service: switch.turn_off
- id: '1595577722294'
  alias: Window Fan Off
  description: ''
  trigger:
  - below: '74'
    entity_id: sensor.bedroom_temperature
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.sonoff2
    service: switch.turn_off
