homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 475
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include include/customize.yaml
  whitelist_external_dirs:
    - /config
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 172.30.33.4
    - type: homeassistant

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3

api:
config:
discovery:
frontend:
  javascript_version: latest
  themes: !include www/themes.yaml
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
map:
mobile_app:
sun:
system_health:
updater:
  include_used_components: true

####################################################
#                     Includes                     #
####################################################
alexa: !include include/alexa.yaml
automation: !include_dir_merge_list automation/
binary_sensor: !include include/binary_sensors.yaml
fan: !include include/fan.yaml
group: !include_dir_merge_named group
history: !include include/history.yaml
input_boolean: !include include/input_boolean.yaml
input_select: !include include/input_select.yaml
light: !include include/lights.yaml
logger: !include include/logger.yaml
media_player: !include include/media_players.yaml
person: !include include/person.yaml
recorder: !include include/recorder.yaml
# scene: !include_dir_merge_list scene ## Converted scenes to scripts
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensors/
# speedtestdotnet: !include include/speedtest.yaml #Pi3 cant detect past 100mb using Unifi USG via Nodered
switch: !include include/switches.yaml
zone: !include include/zones.yaml

####################################################
#                   Integrations                   #
####################################################
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      include_devices:
        - "Echo Dot Main"
        - "Echo Dot Bedroom"
        - "Echo Input"

blueiris:
  host: !secret blueiris_host
  port: !secret blueiris_port
  # [optional] Blue Iris admin username and password
  username: !secret blueiris_admin_username
  password: !secret blueiris_admin_password
  # # List of camera objects
  camera:
    - id: frontyard
      name: "Front Yard"
      room: "Exterior"
    - id: frontdoor
      name: "Front Door"
      room: "Exterior"
    - id: sideyard
      name: "Side Yard"
      room: "Exterior"
    - id: backyard
      name: "Back Yard"
      room: "Exterior"
    - id: motioneye
      name: "MotionEye"
      room: "Exterior"

camera:
  - platform: blueiris

device_tracker:
  - platform: mqtt_json
    devices:
      david_zanzito: zanzito/david/location
      georgina_zanzito: zanzito/georgina/location

ecobee:
  api_key: !secret ecobee_api_key

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

hacs: #https://custom-components.github.io/hacs/installation/configuration/
  token: !secret hacs

mqtt:
  broker: !secret Mosq_broker
  port: !secret Mosq_port
  username: !secret Mosq_username
  password: !secret Mosq_password
  client_id: home-assistant
  keepalive: 60

notify:
  - platform: alexa_media
    name: alexa_media
  - name: telbot_david
    platform: telegram
    chat_id: !secret telegram_chatID_David
  # - name: telbot_georgina
  #   platform: telegram
  #   chat_id: !secret telegram_chatID_Georgina
  # - name: telbot_mark
  #   platform: telegram
  #   chat_id: !secret telegram_chatID_Mark

panel_custom:
  - name: floorplan
    sidebar_title: Alarm Panel
    sidebar_icon: mdi:shield-home
    url_path: floorplan
    config:
      hide_app_toolbar:
      config: /local/custom_ui/floorplan/floorplan.yaml
  # - name: clock
  #   sidebar_title: Alarm Clock
  #   sidebar_icon: mdi:clock
  #   url_path: clock
  #   config:
  #     hide_app_toolbar:
  #     config: /local/custom_ui/floorplan/floorclock.yaml

<<<<<<< HEAD
# samsungtv:     # Moved to UI Integration vs yaml config
=======
# samsungtv:
>>>>>>> 6242ccaeaadc264f1b2fbb9b2ede8cbde4a3a6da
#   - host: !secret samsungtv_host

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_token
    allowed_chat_ids:
      - !secret telegram_chatID_David
      # - !secret telegram_chatID_Georgina
      # - !secret telegram_chatID_Mark

# tradfri:
#   host: !secret tradfri_host

weather:
  - platform: darksky
    api_key: !secret darksky_api
