homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 475
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include integrations/customize.yaml
  allowlist_external_dirs:
    - /config
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 172.30.33.4
        - 192.168.1.109
    - type: homeassistant

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3

api:
config:
discovery:
frontend:
  javascript_version: latest
  themes: !include www/themes.yaml

lovelace: !include lovelace.yaml

map:
mobile_app:
sun:
system_health:
updater:
  include_used_components: true

####################################################
#               Included Integrations              #
####################################################
alexa: !include integrations/alexa.yaml
automation: !include_dir_merge_list integrations/automation/
binary_sensor: !include integrations/binary_sensors.yaml
fan: !include integrations/fan.yaml
group: !include_dir_merge_named integrations/group
history: !include integrations/history.yaml
input_boolean: !include integrations/input_boolean.yaml
input_select: !include integrations/input_select.yaml
light: !include_dir_merge_list integrations/light
logger: !include integrations/logger.yaml
media_player: !include integrations/media_players.yaml
# person: !include integrations/person.yaml
recorder: !include integrations/recorder.yaml
script: !include_dir_merge_named integrations/script
sensor: !include_dir_merge_list integrations/sensors/
switch: !include integrations/switches.yaml
zone: !include integrations/zones.yaml

####################################################
#                   Integrations                   #
####################################################
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      include_devices:
        - "Echo Dot Main"
        - "Echo Dot Bedroom"
        - "Echo Input"

browser_mod:
  prefix: "browser_"

ecobee:
  api_key: !secret ecobee_api_key

deebot:
    username: !secret ECOVACS_USERNAME
    password: !secret ECOVACS_PASSWORD
    country: !secret TWO_LETTER_COUNTRY_CODE
    continent: !secret TWO_LETTER_CONTINENT_CODE

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

# hacs: #https://custom-components.github.io/hacs/installation/configuration/
#   token: !secret hacs

mqtt:
  broker: !secret Mosq_broker
  port: !secret Mosq_port
  username: !secret Mosq_username
  password: !secret Mosq_password
  client_id: home-assistant
  keepalive: 60
  # discovery: true
  # discovery_prefix: hassio/falcon/player/FPP/ha

notify:
  - platform: alexa_media
    name: alexa_media
  - name: telbot_david
    platform: telegram
    chat_id: !secret telegram_chatID_David
  # - name: telbot_georgina
  #   platform: telegram
  #   chat_id: !secret telegram_chatID_Georgina
  # - name: telbot_mark
  #   platform: telegram
  #   chat_id: !secret telegram_chatID_Mark

panel_custom:
  - name: floorplan
    sidebar_title: Wall Panel
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config:
      hide_app_toolbar:
      config: /local/custom_ui/floorplan/floorplan.yaml

# samsungtv:
#   - host: !secret samsungtv_host

# solaredge:
#   api_key: !secret solaredge_api
#   site_id: !secret solaredge_siteid

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_token
    allowed_chat_ids:
      - !secret telegram_chatID_David
      # - !secret telegram_chatID_Georgina
      # - !secret telegram_chatID_Mark

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
