title: Home
background: center / cover no-repeat url("/local/background3.jpg") fixed
views:
  - !include lovelace/home.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/device_status.yaml
  - !include lovelace/ha.yaml
  - !include lovelace/connected_devices.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/media_players.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/test.yaml
  # - !include lovelace/floorplan.yaml
