####################################################
#                    RESOURCES                     #
####################################################

resources:
  #https://github.com/thomasloven/lovelace-slider-entity-row
  - url: /local/slider-entity-row.js
    type: js
  # https://github.com/custom-cards/tracker-card
  # - url: /customcards/github/custom-cards/tracker-card.js?track=true
  #   type: module
  #https://github.com/custom-cards/vertical-stack-in-card
  - url: /local/vertical-stack-in-card.js?v=v0.1.3
    type: js
  # # Add to the version number at the end of URL when updating.
  # - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
  #   type: module

title: Home
background: center / cover no-repeat url("/local/background3.jpg") fixed
views:
  - !include lovelace/home.yaml
  - !include lovelace/cameras.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/device_status.yaml
  - !include lovelace/media_players.yaml
  - !include lovelace/ha.yaml
  - !include lovelace/connected_devices.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/automations.yaml
  - !include lovelace/blueiris.yaml
  - !include lovelace/insteon.yaml