 ### Control a Pixel Overlay Model via Home Assistant's MQTT Light interface. The Pixel Overlay Model is treated as a C9s light.
# hassio/falcon/player/FPP/light/${MODELNAME}/cmd
# hassio/falcon/player/FPP/light/${MODELNAME}/state

- platform: mqtt
  schema: json
  name: All Exterior C9s
  state_topic: "hassio/falcon/player/FPP/ha/light/All Exterior C9s/state"
  command_topic: "hassio/falcon/player/FPP/ha/light/All Exterior C9s/cmd"
  brightness: true
  rgb: true
  effect: false
  qos: 0

# - platform: mqtt
#   schema: json
#   name: Left Section C9s
#   state_topic: "hassio/falcon/player/FPP/light/Left Section/state"
#   command_topic: "hassio/falcon/player/FPP/light/Left Section/cmd"
#   brightness: true
#   rgb: true

# - platform: mqtt
#   schema: json
#   name: Mid Section C9s
#   state_topic: "hassio/falcon/player/FPP/light/Mid Section/state"
#   command_topic: "hassio/falcon/player/FPP/light/Mid Section/cmd"
#   brightness: true
#   rgb: true

# - platform: mqtt
#   schema: json
#   name: Right Section C9s
#   state_topic: "hassio/falcon/player/FPP/light/Right Section/state"
#   command_topic: "hassio/falcon/player/FPP/light/Right Section/cmd"
#   brightness: true
#   rgb: true
