# LIGHTING GROUPS
# https://www.home-assistant.io/integrations/light.group/

- platform: group
  name: Bedroom
  entities:
    - light.david_nightstand
    - light.georgina_nightstand
    - light.main_bedroom_fanlinc #Master Fanlinc Light
    # - light.main_bedroom_keypad_main

- platform: group
  name: Dining Room
  entities:
    - light.dining_floor_lamp
    - light.dining_table

- platform: group
  name: Dining Table
  entities:
    - light.dining_table_light
    - light.dining_room_switch

- platform: group
  name: Exterior Lights
  entities:
    - light.porch_light
    - light.sideyard_light

- platform: group
  name: Garage Lights
  entities:
    - light.garage_inside #Inner Dooor Switch
    - light.garage_side #Side Door Switch

- platform: group
  name: Interior Lights
  entities:
    - light.dining_room
    - light.garage_lights
    - light.living_room
    - light.kitchen
    - light.office
#     # - switch.sonoff1 #Floor Lamp / Christmas Tree

- platform: group
  name: Kitchen
  entities:
    - light.kitchen_down_lights
    - light.kitchen_pendants
    - light.kitchen_wetbar_rgbw

- platform: group
  name: Kitchen Pendants
  entities:
    - light.kitchen_pendant_1
    - light.kitchen_pendant_2

- platform: group
  name: Living Room
  entities:
    - light.living_room_light_1
    - light.living_room_light_2

- platform: group
  name: Office
  entities:
    - light.office_desk_light
    - light.office_fanlinc
    # - light.office_keypad_main

- platform: group
  name: Night Stands
  entities:
    - light.david_nightstand
    - light.georgina_nightstand
