
#https://home-assistant.io/components/sensor/

####################################################
#               CERTIFICATE EXPIRY                 #
####################################################

#https://home-assistant.io/components/sensor.cert_expiry/
- platform: cert_expiry
  host: !secret external_url
  # name: Lets Encrypt Expiration Depricated v0.109