####################################################
#                    FILESIZE                      #
####################################################

#https://www.home-assistant.io/components/sensor.filesize/
- platform: filesize
  file_paths:
    - !secret filesize_homeassistant_db
    - !secret filesize_homeassistant_log