- platform: template
  scan_interval: 30000
  sensors:
    floorplan_date:
      friendly_name: 'Date'
      entity_id: sun.sun
      value_template: >-
        {{now().strftime("%A, %B %d")}}
       
- platform: template
  sensors:
    floorplan_time:
      friendly_name: 'Time'
      entity_id: sensor.time
      value_template: >-
        {{ as_timestamp(now()) | timestamp_custom("%-I:%M %p")}}
    clock_time:
      friendly_name: 'Clock Time'
      entity_id: sensor.time
      value_template: >-
        {{ as_timestamp(now()) | timestamp_custom("%-I:%M %p")}}