
# - platform: google_wifi

# - platform: zoneminder

# Think I fixed the previous template that was broken. Need to test live
- platform: rest
  resource: http://www.webcal.fi/cal.php?id=335&format=json&start_year=current_year&end_year=current_year&tz=America%2FLos_Angeles
  name: Flag
  scan_interval: 14400
  value_template: >-
    {%- set now_string = now().strftime('%Y-%m-%d') %}
    {% for day_val in value_json if day_val.date == now_string  %}
      True
      {% else %}
      False
    {% endfor -%}

# XBOX LIVE API Connect
# - platform: xbox_live
#   api_key: !secret xbox_api
#   scan_interval: 30
#   xuid:
#     - !secret xbox_user_1 #Myself
#     - !secret xbox_user_2 #Wife
#     - !secret xbox_user_3 #Terry
#     - !secret xbox_user_4 #Mike

