####################################################
#                      MQTT                        #
####################################################
#https://www.home-assistant.io/components/sensor.mqtt/

# Device Battery Status
- platform: mqtt
  name: "Georgina Battery Level"
  state_topic: "zanzito/georgina/battery_level"
  unit_of_measurement: "%"
- platform: mqtt
  name: "David Battery Level"
  state_topic: "zanzito/david/battery_level"
  unit_of_measurement: "%"
