####################################################
#                      MQTT                        #
####################################################
#https://www.home-assistant.io/components/sensor.mqtt/

# WallPanel Sensor Data
- platform: mqtt
  name: "WallPanel Battery Level"
  state_topic: "wallpanel/mywallpanel/sensor/battery"
  unit_of_measurement: "%"
  value_template: "{{ value_json.value }}"
- platform: mqtt
  name: "WallPanel Charging"
  state_topic: "wallpanel/mywallpanel/sensor/battery"
  value_template: "{{ value_json.charging }}"
- platform: mqtt
  name: "WallPanel Light Level"
  state_topic: "wallpanel/mywallpanel/sensor/light"
  unit_of_measurement: "lx"
  value_template: "{{ value_json.value }}"
- platform: mqtt
  name: "WallPanel ScreenOn"
  state_topic: "wallpanel/mywallpanel/state"
  value_template: "{{ value_json.screenOn }}"
- platform: mqtt
  name: "WallPanel ScreenBrightness"
  state_topic: "wallpanel/mywallpanel/state"
  value_template: "{{ value_json.brightness }}"
- platform: mqtt
  name: "WallPanel CurrentUrl"
  state_topic: "wallpanel/mywallpanel/state"
  value_template: "{{ value_json.currentUrl }}"
