- platform: mqtt
  schema: json
  name: "Master Ceiling Light" #Fanlinc1
  state_topic: "insteon/3f.d9.93/state"
  command_topic: "insteon/3f.d9.93/level"
  brightness: true
  qos: 2

- platform: mqtt
  schema: json
  name: "Office Ceiling Light" #Fanlinc2
  state_topic: "insteon/47.99.0f/state"
  command_topic: "insteon/47.99.0f/level"
  brightness: true
  qos: 2

# - platform: mqtt
#   schema: json
#   name: "Guest Ceiling Light" #Fanlinc3
#   state_topic: "insteon/3f.d9.93/state"
#   command_topic: "insteon/3f.d9.93/level"
#   brightness: true
#   qos: 2

- platform: mqtt
  schema: json
  name: "Patio Lights" #Dimmer1 (Micro)
  state_topic: "insteon/4f.b2.53/state"
  command_topic: "insteon/4f.b2.53/level"
  brightness: true
  qos: 2

- platform: mqtt
  schema: json
  name: "Dinning Table Light" #Dimmer2 (Micro)
  state_topic: "insteon/4f.b0.cf/state"
  command_topic: "insteon/4f.b0.cf/level"
  brightness: true
  qos: 2

- platform: mqtt
  schema: json
  name: "Dinning Room Switch" #Dimmer3 (Switch)
  state_topic: "insteon/43.3f.1c/state"
  command_topic: "insteon/43.3f.1c/level"
  brightness: true
  qos: 2

- platform: mqtt
  schema: json
  name: "Kitchen Down Lights" #Dimmer5
  state_topic: "insteon/55.94.84/state"
  command_topic: "insteon/55.94.84/level"
  brightness: true
  qos: 2

- platform: mqtt
  schema: json
  name: Whole House RGB
  state_topic: "hassio/falcon/player/FPP/light/Whole House/state"
  command_topic: "hassio/falcon/player/FPP/light/Whole House/cmd"
  brightness: true
  rgb: true

# - platform: mqtt
#   schema: json
#   name: Left Section RGB
#   state_topic: "hassio/falcon/player/FPP/light/Left Section/state"
#   command_topic: "hassio/falcon/player/FPP/light/Left Section/cmd"
#   brightness: true
#   rgb: true

# - platform: mqtt
#   schema: json
#   name: Mid Section RGB
#   state_topic: "hassio/falcon/player/FPP/light/Mid Section/state"
#   command_topic: "hassio/falcon/player/FPP/light/Mid Section/cmd"
#   brightness: true
#   rgb: true

# - platform: mqtt
#   schema: json
#   name: Right Section RGB
#   state_topic: "hassio/falcon/player/FPP/light/Right Section/state"
#   command_topic: "hassio/falcon/player/FPP/light/Right Section/cmd"
#   brightness: true
#   rgb: true