###  INSTEON MQTT PLM CONTROL
- platform: mqtt
  name: 'Garage Inside' #Switch1
  state_topic: 'insteon/48.7a.4e/state'
  command_topic: 'insteon/48.7a.4e/set'
  optimistic: true
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
  retain: true
- platform: mqtt
  name: 'Garage Side' #Switch2
  state_topic: 'insteon/48.79.ba/state'
  command_topic: 'insteon/48.79.ba/set'
  optimistic: true
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
  retain: true
- platform: mqtt
  name: 'Garage Utility Outlet' #Switch3
  state_topic: 'insteon/54.4b.92/state'
  command_topic: 'insteon/54.4b.92/set'
  optimistic: true
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
  retain: true

  #------------------------------------------------------------------------
  # Keypad Linc
  # 6 button and 8 button keypads have use the following button numbers:
  #    1 on           1       2
  #  3       4        3       4
  #  5       6        5       6
  #    1 off          7       8
  #------------------------------------------------------------------------
# Master Keypad Switch
- platform: mqtt
  name: 'Master Keypad Main'
  state_topic: 'insteon/46.fb.73/state/1'
  command_topic: 'insteon/46.fb.73/set/1'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Master Keypad A'
  state_topic: 'insteon/46.fb.73/state/3'
  command_topic: 'insteon/46.fb.73/set/3'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Master Keypad B'
  state_topic: 'insteon/46.fb.73/state/4'
  command_topic: 'insteon/46.fb.73/set/4'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Master Keypad C'
  state_topic: 'insteon/46.fb.73/state/5'
  command_topic: 'insteon/46.fb.73/set/5'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Master Keypad D'
  state_topic: 'insteon/46.fb.73/state/6'
  command_topic: 'insteon/46.fb.73/set/6'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1

# Office Keypad Switch
- platform: mqtt
  name: 'Office Keypad Main'
  state_topic: 'insteon/51.79.ba/state/1'
  command_topic: 'insteon/51.79.ba/set/1'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Office Keypad A'
  state_topic: 'insteon/51.79.ba/state/3'
  command_topic: 'insteon/51.79.ba/set/3'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Office Keypad B'
  state_topic: 'insteon/51.79.ba/state/4'
  command_topic: 'insteon/51.79.ba/set/4'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Office Keypad C'
  state_topic: 'insteon/51.79.ba/state/5'
  command_topic: 'insteon/51.79.ba/set/5'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Office Keypad D'
  state_topic: 'insteon/51.79.ba/state/6'
  command_topic: 'insteon/51.79.ba/set/6'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1

# Living Room Keypad Switch
- platform: mqtt
  name: 'Living Room Keypad Main'
  state_topic: 'insteon/50.a1.f8/state/1'
  command_topic: 'insteon/50.a1.f8/set/1'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Living Room Keypad A'
  state_topic: 'insteon/50.a1.f8/state/3'
  command_topic: 'insteon/50.a1.f8/set/3'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Living Room Keypad B'
  state_topic: 'insteon/50.a1.f8/state/4'
  command_topic: 'insteon/50.a1.f8/set/4'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Living Room Keypad C'
  state_topic: 'insteon/50.a1.f8/state/5'
  command_topic: 'insteon/50.a1.f8/set/5'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
- platform: mqtt
  name: 'Living Room Keypad D'
  state_topic: 'insteon/50.a1.f8/state/6'
  command_topic: 'insteon/50.a1.f8/set/6'
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1

#### SonOff Relays
- platform: mqtt
  name: 'sonoff1'
  command_topic: 'cmnd/sonoff1/power'
  state_topic: 'stat/sonoff1/POWER'
  optimistic: true
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
  retain: true
- platform: mqtt
  name: 'sonoff2'
  command_topic: 'cmnd/sonoff2/power'
  state_topic: 'stat/sonoff2/POWER'
  optimistic: true
  payload_on: 'ON'
  payload_off: 'OFF'
  qos: 1
  retain: true
# Bricked on Tasmoto OTA Firmware Update
# - platform: mqtt
#   name: 'sonoff_pow3'
#   command_topic: 'cmnd/sonoff_pow3/power'
#   state_topic: 'stat/sonoff_pow3/POWER'
#   optimistic: true
#   payload_on: 'ON'
#   payload_off: 'OFF'
#   qos: 1
#   retain: true

#### Shelly Relays
- platform: mqtt
  name: 'Shelly1pm MQTT'
  state_topic: 'shellies/shelly1pm-00139E/relay/0'
  command_topic: 'shellies/shelly1pm-00139E/relay/0/command'
  payload_on: 'on'
  payload_off: 'off'
  retain: true
