# Turn on fan_min_on_time if sensors are within 3 degress
- alias: 'Ecobee Fan on'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.ecobee_compare_temps
      above: 3
  condition:
    - condition: state
      entity_id: group.window_sensors
      state: 'off'
  action:
    - service: climate.ecobee_set_fan_min_on_time
      data:
        entity_id: climate.echo
        fan_min_on_time: 20

# Turn off fan_min_on_time if sensors are within 3 degress
- alias: 'Ecobee Fan off'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.ecobee_compare_temps
      below: 3
  action:
  - service: climate.ecobee_set_fan_min_on_time
    data:
      entity_id: climate.echo
      fan_min_on_time: 0

# Turn on celling fan while sleeping
- alias: 'Ceiling Fan On while Sleeping'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_temperature
      above: 75
  condition:
    - condition: state
      entity_id: group.sleep_status
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.master_bedroom_fan_low

# Turn ON Climate Control to Auto if windows closed
- alias: 'Ecobee set to Auto'
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.window_sensors
      from: 'on'
      to: 'off'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.echo
        hvac_mode: auto

# Turn OFF Climate Control if windows opeded
- alias: 'Ecobee set to OFF'
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.window_sensors
      from: 'off'
      to: 'on'
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.echo
        hvac_mode: 'off'

# Set preset back to sleep mode if people sleeping
- alias: Ecobee preset mode Sleep
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.sleep_status
      to: 'on'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.echo
        preset_mode: 'Sleep'

# Set preset back to sleep mode if people sleeping
- alias: Ecobee preset mode Resume
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.sleep_status
      from: 'on'
      to: 'off'
  action:
    - service: ecobee.resume_program
      entity_id: climate.echo

