#### MASTER BEDROOM FAN
- alias: 'Bedroom Fan On while Sleeping'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_temperature
      above: 75
  condition:
    - condition: state
      entity_id: group.sleep_status
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.master_bedroom_fan_low

- alias: 'Bedroom Fan Off while Sleeping'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_temperature
      below: 72
  condition:
    - condition: state
      entity_id: group.sleep_status
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.master_bedroom_fan_off

#### OFFICE FAN
- alias: 'Office Fan On while Occupied'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.office_temperature
      above: 79
  condition:
    - condition: state
      entity_id: binary_sensor.office_occupancy
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.office_fan_low

- alias: 'Office Fan Off while Occupied'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.office_temperature
      below: 77
    - platform: state
      entity_id: binary_sensor.office_occupancy
      to: 'off'
  # condition:
  #   - condition: state
  #     entity_id: binary_sensor.office_occupancy
  #     state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.office_fan_off