- alias: 'Christmas Tree on when home'
  initial_state: False
  trigger:
    - platform: state
      entity_id:
        - person.david
        - person.georgina
      to: 'home'
  condition:
    - condition: template
      value_template: >
        {% if is_state('input_boolean.david_status', 'off') %} true
        {% elif is_state('input_boolean.georgina_status', 'off') %} true
        {% else %} false {% endif %}
  action:
    service: homeassistant.turn_on
    entity_id: light.dinning_room_switch #Christmas Tree

- alias: 'Christmas Tree off when away'
  initial_state: False
  trigger:
    - platform: state
      entity_id:
        - person.david
        - person.georgina
      from: 'home'
      to: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id: light.dinning_room_switch #Christmas Tree

#####  Exterior RBG lights on at sunset  #####
- alias: 'Monthly Holiday Color Scene ON'
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      # Can be a positive or negative number
      below: -4.0
  action:
    - service: script.monthly_color_scene

#####  Exterior RGB lights OFF  #####
- alias: 'Monthly Holiday Color Scene OFF'
  initial_state: True
  trigger:
    - platform: sun
      event: sunrise
      offset: '-00:30:00'
  action:
    - service: script.monthly_color_off
