#####  Turn Side light on with motion  #####
- alias: "Side Light on by camera sensor"
  initial_state: True
  # hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.sideyard_motion_sensor
      from: 'off'
      to: 'on'
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    - service: homeassistant.turn_on
      entity_id: light.sideyardww
      data:
        brightness: 150
        transition: 2

#####  Turn Side light off with motion  #####
- alias: "Side Light off by camera sensor"
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.sideyard_motion_sensor
      to: 'off'
      for:
        minutes: 10
  condition:
      condition: or  # 'when dark' condition: either after sunset or before sunrise
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    - service: homeassistant.turn_off
      entity_id: light.sideyardww
      data:
#        brightness: 0
        transition: 2

####### Test
- alias: "Turn on off garage lights when there is movement"
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_motion_status
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_motion_status
      to: 'off'
      for:
        minutes: 20
  action:
    - service_template: '{% if trigger.to_state.state == "on" %}switch.turn_on{% elif trigger.to_state.state == "off" %}switch.turn_off{% endif %}'
      entity_id: group.garage
