- alias: "Georgina Leaving Work"
  initial_state: True
  hide_entity: True
  trigger:
    - platform: state
      entity_id: person.georgina
      from: 'JWC Factory'
      to: 'not_home'
  action:
    - service: mqtt.publish
      data_template:
        topic: zanzito/david/notification
        payload: 'Georgina has left Work as of {{now().strftime("%H:%M")}}'
        retain: false

- alias: "Georgina is Home"
  initial_state: True
  hide_entity: True
  trigger:
    - platform: state
      entity_id: person.georgina
      from: 'not_home'
      to: 'home'
  condition:
    - condition: numeric_state
      entity_id: sensor.time_online
      above: .5
    - condition: template 
      value_template: >
        {% if is_state('input_boolean.david_status', 'off') %} true
        {% elif is_state('person.david', 'home') %} true
        {% else %} false {% endif %}
    - condition: state
      entity_id: person.georgina
      state: 'not_home'
      for:
        minutes: 5
  action:
    - service: mqtt.publish
      data_template:
        topic: zanzito/david/notification
        payload: 'Georgina is Home as of {{now().strftime("%H:%M")}}'
        retain: false
    - service: script.audio_notify
      data_template:
        tts_msg: "Georgina is Now Home"
        mplayer: "echo_dot_bedroom"

- alias: "David is Home"
  initial_state: True
  hide_entity: True
  trigger:
    - platform: state
      entity_id: person.david
      to: 'home'
  condition:
    - condition: numeric_state
      entity_id: sensor.time_online
      above: .5
    - condition: template 
      value_template: >
        {% if is_state('input_boolean.georgina_status', 'off') %} true
        {% else %} false {% endif %}
  action:
    - service: mqtt.publish
      data_template:
        topic: zanzito/georgina/notification
        payload: 'David is Home as of {{now().strftime("%H:%M")}}'
        retain: false
    # - service: script.audio_notify
    #   data_template:
    #     tts_msg: "David is Now Home"
    #     mplayer: "echo_dot_bedroom"