- alias: "Wake up David for Work"
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.my_event_offset_2
      to: 'on'
  condition: 
    - condition: template 
      value_template: >
        {% if is_state('person.david', 'home') %} true
        {% else %} false {% endif %}
    - condition: template 
      value_template: >
        {% if state_attr('calendar.disney_work_schedule', 'description') == None  %} true
        {% else %} false {% endif %}
  action:
    # - service: mqtt.publish
    #   data_template:
    #     topic: zanzito/david/alarm/play
    #     payload: 'Wake up for work'
    #     retain: false
    - service: script.lights_on_when_waking_up
    - service: notify.mobile_app_david_pixel_3a_app
      data:
        title: "Wake UP"
        message: "Its time to wake up for work."
        data:
          channel: Alarm # name of the channel you wish to create or utilize

- alias: "Tell David to leave for work"
  initial_state: True
  trigger:
    - platform: state
      entity_id: sensor.my_event_offset_1
      to: 'on'
  condition:
    - condition: template 
      value_template: >
        {% if is_state('person.david', 'home') %} true
        {% elif is_state('person.david', 'not_home') %} true
        {% else %} false {% endif %}
    - condition: template 
      value_template: >
        {% if state_attr('calendar.disney_work_schedule', 'description') == None  %} true
        {% else %} false {% endif %}
  action:
    # - service: mqtt.publish
    #   data_template:
    #     topic: zanzito/david/alarm/play
    #     payload: 'Time to leave for Work'
    #     retain: false