- alias: "Georgina is Awake"
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.georgina_status
      to: 'off'
  action:
    - service: script.lights_on_when_waking_up

- alias: "Reset David Sleeping"
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.david_phone_charging
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.david_status
      state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.david_status

- alias: "Reset Georgina Sleeping"
  initial_state: True
  trigger:
    - platform: state
      entity_id: input_boolean.georgina_phone_charging
      from: 'on'
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.georgina_status
      state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.georgina_status