- alias: "Wallpanel Motion Detected"
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.wallpanel_ideal

- alias: "Wallpanel Motion Clear"
  initial_state: True
  trigger:
    - platform: state
      entity_id: binary_sensor.motion
      from: 'on'
      to: 'off'
      # for:
      #   minutes: 1
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wallpanel_ideal

- alias: 'Wallpanel Off when leaving'
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.persons
      to: 'not_home'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.wallpanel_blackout

- alias: 'Wallpanel on when home'
  initial_state: True
  trigger:
    - platform: state
      entity_id: 
      - person.david
      - person.georgina
      from: 'not_home'
      to: 'home'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.wallpanel_blackout

- alias: 'Wallpanel on when awake'
  initial_state: True
  trigger:
    - platform: state
      entity_id: 
      - input_boolean.david_status
      - input_boolean.georgina_status
      from: 'on'
      to: 'off'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.wallpanel_blackout