- alias: "Wallpanel Motion Detected"
  trigger:
    - platform: state
      entity_id: binary_sensor.wallpanel_motion_sensor
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.wallpanel_ideal
    - service: script.wallpanel_full_night

- alias: "Wallpanel Motion Clear"
  trigger:
    - platform: state
      entity_id: binary_sensor.wallpanel_motion_sensor
      from: 'on'
      to: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wallpanel_ideal
    - service: script.wallpanel_dim

- alias: "Wallpanel Dim"
  trigger:
    - platform: state
      entity_id: binary_sensor.wallpanel_motion_sensor
      from: 'on'
      to: 'off'
      for:
        minutes: 10
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wallpanel_ideal
    - service: script.wallpanel_1_percent

- alias: 'Wallpanel Off when leaving'
  trigger:
    - platform: state
      entity_id: group.persons
      to: 'not_home'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.wallpanel_blackout
    - service: script.wallpanel_1_percent

# - alias: 'Wallpanel on when home'
#   trigger:
#     - platform: state
#       entity_id: 
#       - person.david
#       - person.georgina
#       from: 'not_home'
#       to: 'home'
#   action:
#     - service: input_boolean.turn_off
#       entity_id: input_boolean.wallpanel_blackout
#     - service: mqtt.publish
#       data_template:
#         topic: wallpanel/mywallpanel/command
#         payload: "{\"brightness\": \"200\"}"
#         retain: false

# - alias: 'Wallpanel on when awake'
#   trigger:
#     - platform: state
#       entity_id: 
#       - input_boolean.david_status
#       - input_boolean.georgina_status
#       from: 'on'
#       to: 'off'
#   action:
#     - service: input_boolean.turn_off
#       entity_id: input_boolean.wallpanel_blackout
#     - service: mqtt.publish
#       data_template:
#         topic: wallpanel/mywallpanel/command
#         payload: "{\"brightness\": \"200\"}"
#         retain: false
